freebsd_task:
  freebsd_instance:
    image_family: freebsd-14-3
    cpu: 4
    memory: 4G
  install_script:
    - pkg update
    - pkg install -y pkgconf cmake gmake capstone4 GraphicsMagick png
          devel/sdl20 devel/libedit
  script:
    - ./configure --enable-debug || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - ctest -j$(sysctl -n hw.ncpu) test
      || { cat Testing/Temporary/LastTest.log; exit 1; }

xcode_task:
  osx_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  download_cache:
    folder: dl_cache
    populate_script:
      - if [ ! -d dl_cache ]; then mkdir dl_cache ; fi
  install_script:
    - ci/macos-setup.sh
  script:
    - ci/macos-build.sh
  hatari_artifacts:
    path: "hatari-snapshot.zip"
