name: Build Hatari on Windows

on:
  push:
    branches:
    - main
    - test
    tags:
    - v*

jobs:

  msys2:
    runs-on: windows-latest
    env:
      MSYS: winsymlinks:nativestrict
      MSYSTEM: MINGW64
      CHERE_INVOKING: 1
    steps:
    - uses: actions/checkout@v6
    - name: Install libraries
      run: |
        choco install -y --no-progress msys2
        C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -S --needed \
          make pkg-config diffutils \
          mingw-w64-x86_64-cmake \
          mingw-w64-x86_64-gcc \
          mingw-w64-x86_64-SDL2 \
          mingw-w64-x86_64-libpng \
          mingw-w64-x86_64-portmidi \
          mingw-w64-x86_64-libarchive"
    - name: Compile Hatari
      run: |
        C:\tools\msys64\usr\bin\bash -lc "cmake -G 'MSYS Makefiles' ."
        C:\tools\msys64\usr\bin\bash -lc "make -j4"
    - name: Testing
      run: |
        C:\tools\msys64\usr\bin\bash -lc "ctest -j4 --output-on-failure"
